# Generated by Django 2.2.5 on 2019-11-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='end_date',
        ),
    ]
