# Generated by Django 2.0.1 on 2018-11-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_auto_20181125_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='squads.Squad')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
