# Generated by Django 2.2.5 on 2019-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_auto_20191110_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='course_bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='deleted_time',
            field=models.DateTimeField(),
        ),
    ]
