# Generated by Django 2.2.5 on 2019-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20191111_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='deleted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
