# Generated by Django 2.0.1 on 2018-11-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_squadweek_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadweek',
            name='dates',
        ),
    ]
