# Generated by Django 2.2.5 on 2019-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_auto_20191111_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
