# Generated by Django 2.2.5 on 2019-12-01 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_paymenthistory_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
