# Generated by Django 2.2.5 on 2019-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0007_needmoney_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='course_bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='lesson_bill',
            field=models.IntegerField(default=0),
        ),
    ]
