# Generated by Django 2.2.5 on 2019-12-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0008_auto_20191202_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmoney',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='needmoney',
            name='course_bill',
        ),
        migrations.RemoveField(
            model_name='needmoney',
            name='lesson_bill',
        ),
    ]
