# Generated by Django 2.2.5 on 2019-12-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0009_auto_20191203_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('money', models.IntegerField(default=0)),
                ('need_money', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_closed', to='squads.NeedMoney')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
