# Generated by Django 2.0.1 on 2018-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0010_remove_squad_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadweek',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
