# Generated by Django 2.2.5 on 2019-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0010_financeclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='fixed_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='needmoney',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
