# Generated by Django 2.2.5 on 2019-12-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0011_auto_20191207_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceClosed',
        ),
    ]
