# Generated by Django 2.2.5 on 2019-12-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0012_delete_financeclosed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needmoney',
            options={'ordering': ['-id']},
        ),
    ]
