# Generated by Django 2.2.5 on 2019-12-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0013_auto_20191213_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmoney',
            name='fixed_date',
        ),
        migrations.AlterField(
            model_name='needmoney',
            name='start_date',
            field=models.DateField(),
        ),
    ]
