# Generated by Django 2.0.1 on 2018-12-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0013_auto_20181211_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadweek',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='squadweek',
            name='number',
        ),
    ]
