# Generated by Django 2.2.5 on 2019-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0014_auto_20191215_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='pay_day',
            field=models.IntegerField(default=1),
        ),
    ]
