# Generated by Django 2.1.7 on 2019-02-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_curator'),
        ('squads', '0015_squad_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.School'),
        ),
    ]
