# Generated by Django 2.2.5 on 2020-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0016_needmoney_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needmoney',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
