# Generated by Django 2.1.7 on 2019-02-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0016_squad_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='group',
        ),
        migrations.RemoveField(
            model_name='squadcategory',
            name='squads',
        ),
        migrations.RemoveField(
            model_name='squadweek',
            name='squad',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='SquadCategory',
        ),
    ]
