# Generated by Django 2.1.7 on 2019-02-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0017_auto_20190222_1855'),
        ('subjects', '0046_auto_20190222_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SquadWeek',
        ),
    ]
