# Generated by Django 2.2.5 on 2020-05-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0017_auto_20200526_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='age',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='level',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='rating_choices',
        ),
    ]
