# Generated by Django 2.2.5 on 2020-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0018_auto_20200527_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedMoney',
            new_name='BillData',
        ),
    ]
