# Generated by Django 2.1.7 on 2019-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0018_delete_squadweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='squad',
            name='color_back',
            field=models.TextField(default=''),
        ),
    ]
