# Generated by Django 2.2.5 on 2020-06-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0020_auto_20200528_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['-color_back']},
        ),
        migrations.RemoveField(
            model_name='billdata',
            name='pay_day',
        ),
    ]
