# Generated by Django 2.1.7 on 2019-05-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190507_2111'),
        ('squads', '0020_squad_rating_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='curator',
        ),
        migrations.AddField(
            model_name='squad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hissquads', to='accounts.Profile'),
        ),
    ]
