# Generated by Django 2.2.5 on 2020-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0021_auto_20200602_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='crm_notices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdata',
            name='payment_notices',
            field=models.IntegerField(default=0),
        ),
    ]
