# Generated by Django 2.1.7 on 2019-05-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0021_auto_20190510_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='author',
            new_name='teacher',
        ),
    ]
