# Generated by Django 2.2.5 on 2020-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0022_auto_20200602_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='update_notices',
            field=models.BooleanField(default=True),
        ),
    ]
