# Generated by Django 2.2.1 on 2019-06-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_money'),
        ('squads', '0022_auto_20190510_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='squad',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.Office'),
        ),
    ]
