# Generated by Django 2.2.1 on 2019-07-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0023_auto_20190604_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.SubjectAge'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.Office'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='rating_choices',
            field=models.ManyToManyField(related_name='rating_squad_choice', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.School'),
        ),
    ]
