# Generated by Django 2.2.5 on 2020-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0023_billdata_update_notices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdata',
            name='update_notices',
        ),
        migrations.AddField(
            model_name='billdata',
            name='lesson_pay_notice',
            field=models.IntegerField(default=0),
        ),
    ]
