# Generated by Django 2.2.4 on 2019-08-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('squads', '0024_auto_20190704_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='level',
            field=models.ManyToManyField(related_name='groups', to='schools.SubjectLevel'),
        ),
        migrations.RemoveField(
            model_name='squad',
            name='age',
        ),
        migrations.AddField(
            model_name='squad',
            name='age',
            field=models.ManyToManyField(related_name='groups', to='schools.SubjectAge'),
        ),
    ]
