# Generated by Django 2.2.5 on 2020-06-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0024_auto_20200604_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['-color_back', 'id']},
        ),
    ]
