# Generated by Django 2.2.5 on 2019-09-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_crmcard_colour'),
        ('squads', '0025_auto_20190831_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='start_day',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NeedMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('bill', models.IntegerField(default=0)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_money', to='accounts.CRMCard')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_money', to='squads.Squad')),
            ],
        ),
    ]
