# Generated by Django 2.2.5 on 2019-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0026_auto_20190925_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='lesson_bill',
            field=models.IntegerField(default=0),
        ),
    ]
