# Generated by Django 2.2.5 on 2019-09-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0027_needmoney_lesson_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmoney',
            name='lesson_bill',
        ),
    ]
