# Generated by Django 2.2.5 on 2019-10-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_delete_paymenthistory'),
        ('schools', '0045_school_schedule_interval'),
        ('squads', '0029_auto_20190927_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_payments', to='accounts.Profile')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='schools.School')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='squads.Squad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
