# Generated by Django 2.2.5 on 2019-10-08 10:25

from django.db import migrations, models
import squads.models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0030_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='squad',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to=squads.models.upload_location),
        ),
        migrations.AlterField(
            model_name='squad',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to=squads.models.upload_location),
        ),
    ]
