# Generated by Django 2.2.5 on 2019-10-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0032_squadhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='manager',
            new_name='action_author',
        ),
    ]
