# Generated by Django 2.2.5 on 2019-10-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0033_auto_20191022_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadhistory',
            name='new',
        ),
        migrations.RemoveField(
            model_name='squadhistory',
            name='old',
        ),
    ]
