# Generated by Django 2.2.5 on 2019-10-23 06:56

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0033_auto_20191022_0053'),
        ('schools', '0056_auto_20191016_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadhistory',
            name='new',
        ),
        migrations.RemoveField(
            model_name='squadhistory',
            name='old',
        ),
        migrations.CreateModel(
            name='DiscountSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('discount_type', models.CharField(default='', max_length=250)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
