# Generated by Django 2.2.5 on 2019-11-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('squads', '0034_auto_20191023_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='discount_school',
            field=models.ManyToManyField(related_name='nms', to='squads.DiscountSchool'),
        ),
    ]
