# Generated by Django 2.2.5 on 2019-11-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('accounts', '0118_skill_crm_cabinet'),
        ('squads', '0034_auto_20191023_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_discounts', to='accounts.Profile')),
                ('discount_school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='squads.DiscountSchool')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='squads.Squad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
