# Generated by Django 2.2.5 on 2019-11-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('squads', '0034_auto_20191023_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('discount_type', models.CharField(default='', max_length=250)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='needmoney',
            name='discount_school',
            field=models.ManyToManyField(related_name='nms', to='squads.DiscountSchool'),
        ),
    ]
