# Generated by Django 2.2.5 on 2019-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0035_discount_discountschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountschool',
            name='discount_type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
