# Generated by Django 2.2.5 on 2019-11-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_skill_crm_cabinet'),
        ('squads', '0036_discountschool_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_discounts', to='accounts.Profile')),
                ('discount_school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='squads.DiscountSchool')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='squads.Squad')),
                ('students', models.ManyToManyField(related_name='discounts', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
