# Generated by Django 2.2.5 on 2019-11-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0037_auto_20191104_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmoney',
            name='discount_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='squads.DiscountSchool'),
        ),
        migrations.DeleteModel(
            name='DiscountSquad',
        ),
    ]
