# Generated by Django 2.2.5 on 2019-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0040_auto_20191104_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmoney',
            name='discount_school',
        ),
        migrations.AddField(
            model_name='needmoney',
            name='discount_school',
            field=models.ManyToManyField(related_name='nms', to='squads.DiscountSchool'),
        ),
    ]
