# Generated by Django 2.2.5 on 2019-11-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0039_auto_20191104_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needmoney',
            name='discount_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nms', to='squads.DiscountSchool'),
        ),
    ]
