# Generated by Django 2.0.1 on 2018-11-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_homework', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_author', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_author', to='accounts.Profile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subtheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(default='')),
                ('video', models.FileField(default='', upload_to='')),
                ('file', models.FileField(default='', upload_to='')),
                ('youtube_video_link', models.TextField(default='')),
                ('task_list', models.ManyToManyField(related_name='subthemes', to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='subthemes',
            field=models.ManyToManyField(related_name='papers', to='papers.Subtheme'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='papers',
            field=models.ManyToManyField(related_name='lessons', to='papers.Paper'),
        ),
    ]
