# Generated by Django 2.2.5 on 2020-07-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_auto_20200625_0845'),
        ('accounts', '0029_auto_20200724_2100'),
        ('papers', '0002_auto_20200529_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_folders', to='accounts.Profile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='papers.LessonFolder')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_folders', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.TextField(default='lesson')),
                ('object_id', models.IntegerField(null=True)),
                ('action', models.TextField(default='copy')),
                ('previous_parent', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('full', models.BooleanField(default=False)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_cache', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='papers.LessonFolder'),
        ),
    ]
