# Generated by Django 2.2.5 on 2020-08-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20200724_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='typee',
        ),
    ]
