# Generated by Django 2.0.1 on 2018-11-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
