# Generated by Django 2.0.1 on 2018-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_manager'),
        ('papers', '0005_auto_20181129_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='likes',
            field=models.ManyToManyField(related_name='liked_lessons', to='accounts.Profile'),
        ),
    ]
