# Generated by Django 2.2.5 on 2020-08-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_answer_type'),
        ('papers', '0005_auto_20200802_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtheme',
            name='task_list',
        ),
        migrations.AddField(
            model_name='subtheme',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='tasks.Task'),
        ),
    ]
