# Generated by Django 2.2.5 on 2020-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20200806_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subtheme',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='paper',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subtheme',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
