# Generated by Django 2.0.1 on 2018-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_manager'),
        ('papers', '0006_auto_20181129_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_comments', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_lessons', to='accounts.Profile'),
        ),
    ]
