# Generated by Django 2.0.1 on 2018-12-02 20:41

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_status'),
        ('papers', '0007_auto_20181129_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=papers.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiscourses', to='accounts.Profile')),
                ('dislikes', models.ManyToManyField(related_name='disliked_courses', to='accounts.Profile')),
                ('lesson', models.ManyToManyField(related_name='courses', to='papers.Lesson')),
                ('likes', models.ManyToManyField(related_name='liked_courses', to='accounts.Profile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
