# Generated by Django 2.2.5 on 2020-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_auto_20200806_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtheme',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
