# Generated by Django 2.2.5 on 2020-08-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_auto_20200807_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='subthemes',
        ),
        migrations.AddField(
            model_name='subtheme',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='papers.Paper'),
        ),
    ]
