# Generated by Django 2.0.1 on 2018-12-06 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_course_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
