# Generated by Django 2.0.1 on 2018-12-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_status'),
        ('papers', '0010_course_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(default=1, related_name='courses', to='accounts.Profile'),
        ),
    ]
