# Generated by Django 2.0.1 on 2018-12-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lesson',
            new_name='lessons',
        ),
    ]
