# Generated by Django 2.0.1 on 2018-12-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181217_1505'),
        ('papers', '0012_auto_20181206_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='done_by',
            field=models.ManyToManyField(related_name='done_papers', to='accounts.Profile'),
        ),
    ]
