# Generated by Django 2.0.1 on 2018-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_paper_done_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='likes',
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
