# Generated by Django 2.0.1 on 2019-01-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_school'),
        ('papers', '0015_papersolver'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_correctness', models.BooleanField(default=False)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='check_lessons', to='accounts.Profile')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solver', to='papers.Lesson')),
            ],
        ),
    ]
