# Generated by Django 2.0.1 on 2019-01-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_school'),
        ('papers', '0016_lessonsolver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsolver',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='lessonsolver',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='papersolver',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='papersolver',
            name='paper',
        ),
        migrations.AddField(
            model_name='course',
            name='done_by',
            field=models.ManyToManyField(related_name='done_courses', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='done_by',
            field=models.ManyToManyField(related_name='done_lessons', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='LessonSolver',
        ),
        migrations.DeleteModel(
            name='PaperSolver',
        ),
    ]
