# Generated by Django 2.0.1 on 2019-01-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0017_auto_20190109_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtheme',
            name='title',
        ),
    ]
