# Generated by Django 2.0.1 on 2019-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_remove_subtheme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='typee',
            field=models.CharField(default='problem', max_length=250),
        ),
    ]
