# Generated by Django 2.0.1 on 2019-02-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0019_paper_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='slug',
        ),
    ]
