# Generated by Django 2.0.1 on 2019-02-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0020_remove_paper_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['timestamp']},
        ),
    ]
