# Generated by Django 2.0.1 on 2019-02-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0021_auto_20190202_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='likes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
