# Generated by Django 2.0.1 on 2019-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0022_auto_20190204_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimaters',
            field=models.IntegerField(default=0),
        ),
    ]
