# Generated by Django 2.0.1 on 2019-02-04 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0023_lesson_estimaters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='estimaters',
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimater_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
