# Generated by Django 2.0.1 on 2019-02-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0024_auto_20190204_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['rating']},
        ),
    ]
