# Generated by Django 2.1.7 on 2019-02-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0026_auto_20190217_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='access_to_everyone',
            field=models.BooleanField(default=False),
        ),
    ]
