# Generated by Django 2.1.7 on 2019-02-27 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0027_lesson_access_to_everyone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimater_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
