# Generated by Django 2.2.1 on 2019-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0028_auto_20190227_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.School'),
        ),
    ]
