# Generated by Django 2.0.1 on 2018-12-30 08:51

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_profile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=news.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
