# Generated by Django 2.2.5 on 2019-11-07 10:36

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.upload_location)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_posts', to='schools.School')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
