# Generated by Django 2.0.1 on 2019-02-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
