# Generated by Django 2.2.5 on 2020-04-04 20:43

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_crmcard_social_media_id'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_posts', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='done_by',
            field=models.ManyToManyField(related_name='read_posts', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='PostPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('video', models.FileField(default='', upload_to='')),
                ('file', models.FileField(default='', upload_to='')),
                ('youtube_video_link', models.TextField(default='')),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to=news.models.upload_location)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='news.Post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='accounts.Profile')),
                ('dislikes', models.ManyToManyField(related_name='disliked_post_comments', to='accounts.Profile')),
                ('likes', models.ManyToManyField(related_name='liked_post_comments', to='accounts.Profile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Post')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
