# Generated by Django 2.2.5 on 2020-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200404_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpart',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='postpart',
            old_name='image_icon',
            new_name='image',
        ),
        migrations.AddField(
            model_name='postpart',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
