# Generated by Django 2.2.5 on 2020-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200407_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpart',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
