# Generated by Django 2.2.5 on 2020-04-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_postpart_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpart',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
