# Generated by Django 2.2.5 on 2020-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200410_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpart',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postpart',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
