from django.conf.urls import url
from django.contrib import admin

from .views import *
from news.views import blog
app_name = 'Enigmath'
urlpatterns = [
    url(r'^crm/$', about, name='about'),
    url(r'^team/$', team, name='team'),
    url(r'^help/$', help_page, name='help_page'),
    url(r'^pricing/$', pricing, name='pricing'),
    url(r'^login/$', login_page, name='login_page'),
    url(r'^sign_up/$', sign_up, name='sign_up'),
    url(r'^api/login/$', login_view, name='login'),
    url(r'^api/update_pswd/$', update_pswd, name='update_pswd'),
    url(r'^api/add_help_video/$', add_help_video, name='add_help_video'),
    url(r'^api/reset_pswrd/$', reset_pswrd, name='reset_pswrd'),
    url(r'^api/register/$', register_view, name='register'),
    url(r'^reset_pswrd_view/$', reset_pswrd_view, name='reset_pswrd_view'),
    url(r'^category/(?P<id>\d+)/$', category_landing, name='category'),
    url(r'^api/change_subject_url/$', ChangeSubject, name='change_subject_url'),    
    url(r'^lesson/$', hislessons, name='hislessons'),
    url(r'^search/$', search, name='search'),
    url(r'^api/map_search/$', map_search, name='map_search'),
    url(r'^api/map_search_show/$', map_search_show, name='map_search_show'),
    url(r'^api/map_filter/$', map_filter, name='map_filter'),
    url(r'^api/cat_filter/$', cat_filter, name='cat_filter'),
    url(r'^notifications/$', get_notifications, name='get_notifications'),
    url(r'^moderator/$', moderator, name='moderator'),
    url(r'^blog/$', blog, name='blog'),
    url(r'^moderator_run_code/$', moderator_run_code, name='moderator_run_code'),
    url(r'^file_changer/$', file_changer, name='file_changer'),
    url(r'^upload_cards/$', upload_cards, name='upload_cards'),
    url(r'^api/create_school/$', create_school, name='create_school'),
    url(r'^api/create_worker/$', create_worker, name='create_worker'),
    url(r'^api/make_zaiavka/$', make_zaiavka, name='make_zaiavka'),
    url(r'^api/get_request_land/$', get_request_land, name='get_request_land'),
    url(r'^api/another_hint/$', another_hint, name='another_hint'),
    url(r'^api/update_hint/$', update_hint, name='update_hint'),
    url(r'^api/get_cloudpayments_data/$', get_cloudpayments_data, name='get_cloudpayments_data'),
    url(r'^api/cloudpayments/pay/$', cloudpayments_pay, name='cloudpayments_pay'),
    url(r'^api/cloudpayments/fail/$', cloudpayments_fail, name='cloudpayments_fail'),
    url(r'^api/cloudpayments/refund/$', cloudpayments_refund, name='cloudpayments_refund'),
    url(r'^robots.txt', robots, name="robots"),
    url(r'^sitemap', sitemap, name="sitemap"),
    url(r'^$', newland, name='home'),
]