from django.conf.urls import url
from django.contrib import admin

from .views import *
from main.views import get_landing,adilmed

app_name = 'schools'
urlpatterns = [
    url(r'^crm/$', school_crm, name='crm'),
    url(r'^schedule/$', school_schedule, name='schedule'),
    url(r'^students/$', school_students, name='students'),
    url(r'^info/$', school_info, name='info'),
    url(r'^landing/(?P<school_id>\d+)/$', school_landing, name='landing'),
    url(r'^salaries/$', school_salaries, name='salaries'),
    url(r'^courses/$', school_courses, name='courses'),
    url(r'^rating/$', school_rating, name='rating'),
    url(r'^payments/$', school_payments, name='payments'),
    url(r'^api/edit_card/$', edit_card, name='edit_card_url'),
    url(r'^api/add_card/$', add_card, name='add_card_url'),
    url(r'^api/move_card/$', move_card, name='move_card_url'),
    url(r'^api/save_card_as_user/$', save_card_as_user, name='save_card_as_user'),
    url(r'^api/crm_option_url/$', crm_option, name='crm_option_url'),
    url(r'^api/crm_option_url2/$', crm_option2, name='crm_option_url2'),
    url(r'^api/salary_url/$', save_salary, name='salary_url'),
    url(r'^api/save_job_salary/$', save_job_salary, name='save_job_salary'),
    url(r'^api/delete_card/$', delete_card, name='delete_card_url'),
    url(r'^api/open_card_url/$', open_card, name='open_card_url'),
    url(r'^api/show_free_cards/$', show_free_cards, name='show_free_cards'),
    url(r'^api/get_card_squads/$', get_card_squads, name='get_card_squads'),
    url(r'^api/call_helper/$', call_helper, name='call_helper'),
    url(r'^api/change_day_of_week/$', change_day_of_week, name='change_day_of_week'),
    url(r'^api/take_url/$', take_card, name='take_url'),
    url(r'^api/subject_delete_url/$', subject_delete, name='subject_delete_url'),
    url(r'^api/subject_create_url/$', subject_create, name='subject_create_url'),
    url(r'^api/age_delete_url/$', age_delete, name='age_delete_url'),
    url(r'^api/age_create_url/$', age_create, name='age_create_url'),
    url(r'^api/office_delete_url/$', office_delete, name='office_delete_url'),
    url(r'^api/office_create_url/$', office_create, name='office_create_url'),
    url(r'^api/timep_delete_url/$', timep_delete, name='timep_delete_url'),
    url(r'^api/timep_create_url/$', timep_create, name='timep_create_url'),
    url(r'^api/get_landing/$', get_landing, name='get_landing'),
    url(r'^api/search_url/$', search_title, name='search_url'),
    url(r'^api/card_called/$', card_called, name='card_called'),
    url(r'^api/change_manager/$', change_manager, name='change_manager'),
    url(r'^api/change_title_url/$', change_title, name='change_title_url'),
    url(r'^api/create_cabinet_url/$', create_cabinet, name='create_cabinet_url'),
    url(r'^api/save_review_url/(?P<school_id>\d+)/$', save_review, name='save_review_url'),
    url(r'^api/create_social_url/$', create_social, name='create_social_url'),
    url(r'^api/delete_social_url/$', delete_social, name='delete_social_url'),
    url(r'^api/delete_school_banner/', delete_school_banner, name='delete_school_banner'),
    url(r'^(?P<id>\d+)/edit/$', school_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', school_delete, name='delete'),
    url(r'^api/make_zaiavka/(?P<school_id>\d+)/$', make_zaiavka, name='make_zaiavka'),
    url(r'^adilmed/', adilmed, name="adilmed"),
]