from django.conf.urls import url
from django.contrib import admin

from .views import *
from main.views import get_landing,adilmed, get_school_report
from django.views.decorators.csrf import csrf_exempt

app_name = 'schools'
urlpatterns = [
    url(r'^crm/$', school_crm, name='crm'),
    url(r'^schedule/$', school_schedule, name='schedule'),
    url(r'^info/$', school_info, name='info'),
    url(r'^landing/(?P<school_id>\d+)/$', school_landing, name='landing'),
    url(r'^salaries/$', school_salaries, name='salaries'),
    url(r'^rating/$', school_rating, name='rating'),
    url(r'^payments/$', school_payments, name='payments'),
    url(r'^reports/$', get_school_report, name='get_school_report'),
    url(r'^api/edit_card/$', edit_card, name='edit_card_url'),
    url(r'^api/edit_card_mail/$', edit_card_mail, name='edit_card_mail'),
    url(r'^api/add_card/$', add_card, name='add_card_url'),
    url(r'^api/move_card/$', move_card, name='move_card_url'),
    url(r'^api/move_worker/$', move_worker, name='move_worker_url'),
    url(r'^api/add_job/$', add_job, name='add_job'),
    url(r'^api/delete_job/$', delete_job, name='delete_job'),
    url(r'^api/save_card_as_user/$', save_card_as_user, name='save_card_as_user'),
    url(r'^api/predoplata/$', predoplata, name='predoplata'),
    url(r'^api/crm_option_url/$', crm_option, name='crm_option_url'),
    url(r'^api/crm_option_url2/$', crm_option2, name='crm_option_url2'),
    url(r'^api/salary_url/$', save_salary, name='salary_url'),
    url(r'^api/save_job_salary/$', save_job_salary, name='save_job_salary'),
    url(r'^api/delete_card/$', delete_card, name='delete_card_url'),
    url(r'^api/open_card_url/$', open_card, name='open_card_url'),
    url(r'^api/show_free_cards/(?P<school_id>\d+)$', show_free_cards, name='show_free_cards'),
    url(r'^api/get_card_squads/$', get_card_squads, name='get_card_squads'),
    url(r'^api/call_helper/$', call_helper, name='call_helper'),
    url(r'^api/change_day_of_week/$', change_day_of_week, name='change_day_of_week'),
    url(r'^api/take_url/$', take_card, name='take_url'),
    url(r'^api/subject_delete_url/$', subject_delete, name='subject_delete_url'),
    url(r'^api/subject_create_url/$', subject_create, name='subject_create_url'),
    url(r'^api/discounts_delete_url/$', discount_delete, name='discount_delete_url'),
    url(r'^api/discounts_create_url/$', discount_create, name='discount_create_url'),
    url(r'^api/age_delete_url/$', age_delete, name='age_delete_url'),
    url(r'^api/age_create_url/$', age_create, name='age_create_url'),
    url(r'^api/level_delete_url/$', level_delete, name='level_delete_url'),
    url(r'^api/level_create_url/$', level_create, name='level_create_url'),
    url(r'^api/office_delete_url/$', office_delete, name='office_delete_url'),
    url(r'^api/office_create_url/$', office_create, name='office_create_url'),
    url(r'^api/timep_delete_url/$', timep_delete, name='timep_delete_url'),
    url(r'^api/timep_create_url/$', timep_create, name='timep_create_url'),
    url(r'^api/get_landing/$', get_landing, name='get_landing'),
    url(r'^api/search_url/$', search_title, name='search_url'),
    url(r'^api/card_called/$', card_called, name='card_called'),
    url(r'^api/change_manager/$', change_manager, name='change_manager'),
    url(r'^api/change_title_url/$', change_title, name='change_title_url'),
    url(r'^api/create_cabinet_url/$', create_cabinet, name='create_cabinet_url'),
    url(r'^api/save_review_url/(?P<school_id>\d+)/$', save_review, name='save_review_url'),
    url(r'^api/create_social_url/$', create_social, name='create_social_url'),
    url(r'^api/delete_social_url/$', delete_social, name='delete_social_url'),
    url(r'^api/delete_school_banner/', delete_school_banner, name='delete_school_banner'),
    url(r'^api/update_voronka/', update_voronka, name='update_voronka'),
    url(r'^api/new_money_object/', new_money_object, name='new_money_object'),
    url(r'^api/show_money_history/', show_money_history, name='show_money_history'),
    url(r'^api/get_manager_actions/', get_manager_actions, name='get_manager_actions'),
    url(r'^api/get_student_actions/', get_student_actions, name='get_student_actions'),
    url(r'^api/get_teacher_actions/', get_teacher_actions, name='get_teacher_actions'),
    url(r'^api/delete_cabinet/', delete_cabinet, name='delete_cabinet'),
    url(r'^api/make_zaiavka/(?P<school_id>\d+)/$', make_zaiavka, name='make_zaiavka'),
    url(r'^api/get_school_report/(?P<school_id>\d+)/$', get_school_report, name='get_school_report'),
    url(r'^adilmed/', adilmed, name="adilmed"),
    url(r'^api/get_extra_cards/', get_extra_cards, name='get_extra_cards'),
    url(r'^api/get_all_cards_first/', get_all_cards_first, name='get_all_cards_first'),
    url(r'^api/get_all_cards_second/', get_all_cards_second, name='get_all_cards_second'),
    url(r'^api/payment_history/', payment_history, name='payment_history'),
    url(r'^api/get_payment_list/', get_payment_list, name='get_payment_list'),
    url(r'^api/search_crm_cards/', search_crm_cards, name='search_crm_cards'),
    url(r'^api/search_city/', search_city, name='search_city'),
    url(r'^api/filter_crm_cards/', filter_crm_cards, name='filter_crm_cards'),
    url(r'^api/get_card_info/', get_card_info, name='get_card_info'),
    url(r'^api/get_card_dialog/', get_card_info_dialog, name='get_card_dialog'),
    url(r'^api/group_finance/', group_finance, name='group_finance'),
    url(r'^api/send_login_url/', send_login_url, name='send_login_url'),
    url(r'^api/payday_change/', payday_change, name='payday_change'),
    url(r'^api/show_finance_update/', show_finance_update, name='show_finance_update'),
    url(r'^api/update_finance/', update_finance, name='update_finance'),
    url(r'^api/get_schedule/', get_schedule, name='get_schedule'),
    url(r'^api/card_send_mail/$', card_send_mail, name='card_send_mail'),

    url(r'^social_networks_settings/$', social_networks_settings, name='social_networks_settings'),
    url(r'^instagram_connecting/$', instagram_connecting, name='instagram_connecting'),
    url(r'^vk_connecting/$', vk_connecting, name='vk_connecting'),
    url(r'^api/connect_sm/', connect_sm, name='connect_sm'),
    url(r'^api/save_vk_group/', save_vk_group, name='save_vk_group'),
    url(r'^api/vk_get_callback/$', csrf_exempt(vk_get_callback), name='vk_get_callback'),
]