# Generated by Django 2.0.1 on 2019-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='object_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
