# Generated by Django 2.1.7 on 2019-02-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_curator'),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_boards', to='schools.School'),
        ),
        migrations.AddField(
            model_name='document',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_docs', to='schools.School'),
        ),
    ]
