# Generated by Django 2.0.1 on 2019-02-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_document_object_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id']},
        ),
    ]
