# Generated by Django 2.2.5 on 2019-10-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190217_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_docs', to='schools.School'),
        ),
    ]
