# Generated by Django 2.0.1 on 2018-11-22 08:20

import accounts.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.TextField(default='admin2')),
                ('title', models.TextField(default='Летняя программа')),
                ('text', models.TextField(default='text')),
                ('schedule_time_periods', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('folder_image', models.ImageField(blank=True, height_field='height_field2', null=True, upload_to=accounts.models.upload_location, width_field='width_field2')),
                ('height_field2', models.IntegerField(default=0, null=True)),
                ('width_field2', models.IntegerField(default=0, null=True)),
                ('paper_image', models.ImageField(blank=True, height_field='height_field3', null=True, upload_to=accounts.models.upload_location, width_field='width_field3')),
                ('height_field3', models.IntegerField(default=0, null=True)),
                ('width_field3', models.IntegerField(default=0, null=True)),
                ('squad_image', models.ImageField(blank=True, height_field='height_field4', null=True, upload_to=accounts.models.upload_location, width_field='width_field4')),
                ('height_field4', models.IntegerField(default=0, null=True)),
                ('width_field4', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('city', models.TextField(blank=True, default='Алматы', null=True)),
                ('first_name', models.TextField(blank=True, default='', null=True)),
                ('second_name', models.TextField(blank=True, default='', null=True)),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('status', models.TextField(blank=True, default='student', null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('mail', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('director', models.ManyToManyField(default=1, related_name='director_school', to='accounts.Profile')),
                ('managers', models.ManyToManyField(default=1, related_name='managers_school', to='accounts.Profile')),
                ('students', models.ManyToManyField(default=1, related_name='students_school', to='accounts.Profile')),
                ('treners', models.ManyToManyField(default=1, related_name='treners_school', to='accounts.Profile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zaiavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
