# Generated by Django 2.2.5 on 2019-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='parents',
            field=models.CharField(default='', max_length=250),
        ),
    ]
