# Generated by Django 2.2.5 on 2019-11-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_crmcard_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcard',
            options={'ordering': ['-timestamp']},
        ),
    ]
