# Generated by Django 2.0.1 on 2018-11-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
    ]
