# Generated by Django 2.2.5 on 2019-12-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191127_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['is_student', 'first_name']},
        ),
    ]
