# Generated by Django 2.0.1 on 2018-11-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trener',
            field=models.BooleanField(default=False),
        ),
    ]
