# Generated by Django 2.2.5 on 2019-12-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('accounts', '0005_auto_20191202_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMoneyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_money_histories', to='accounts.Profile')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_money_histories', to='schools.School')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
