# Generated by Django 2.2.5 on 2020-03-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_schoolmoneyhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmcard',
            old_name='colour',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='crmcard',
            name='action',
        ),
    ]
