# Generated by Django 2.0.1 on 2018-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181217_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ceo',
            field=models.BooleanField(default=False),
        ),
    ]
