# Generated by Django 2.2.5 on 2020-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cardmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmail',
            name='method',
            field=models.CharField(default='mail', max_length=25),
        ),
    ]
