# Generated by Django 2.2.5 on 2020-03-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cardmail_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmail',
            name='action_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='cardmail',
            name='method',
            field=models.CharField(default='Почта', max_length=100),
        ),
    ]
