# Generated by Django 2.0.1 on 2018-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_is_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
