# Generated by Django 2.2.5 on 2020-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmail',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
