# Generated by Django 2.0.1 on 2018-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181217_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(default=''),
        ),
    ]
