# Generated by Django 2.2.5 on 2020-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cardmail_is_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmail',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cardmail',
            name='method',
            field=models.CharField(default='', max_length=100),
        ),
    ]
