# Generated by Django 2.0.1 on 2019-01-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_curator'),
        ('accounts', '0012_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='profile',
            name='schooll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.School'),
        ),
    ]
