# Generated by Django 2.2.5 on 2020-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200315_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='instagram_access_token',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='instagram_user_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
