# Generated by Django 2.0.1 on 2019-01-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190111_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='schooll',
            new_name='school',
        ),
    ]
