# Generated by Django 2.2.5 on 2020-03-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200317_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='instagram_access_token',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='instagram_user_id',
        ),
        migrations.AlterField(
            model_name='cardmail',
            name='method',
            field=models.CharField(default='', max_length=250),
        ),
    ]
