# Generated by Django 2.2.5 on 2020-03-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_cardmail_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='social_media_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
