# Generated by Django 2.2.5 on 2020-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_crmcard_social_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='crm_age',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_age2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_cabinet',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_office',
        ),
        migrations.AddField(
            model_name='skill',
            name='payment_filter',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
