# Generated by Django 2.2.5 on 2020-05-16 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200510_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0, 0, 0], size=None),
        ),
    ]
