# Generated by Django 2.0.1 on 2019-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190112_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
