# Generated by Django 2.2.5 on 2020-05-19 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_skill_hint_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 1, 1, 1, 1, 1], size=None),
        ),
    ]
