# Generated by Django 2.0.1 on 2019-01-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_is_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='his_messages', to='accounts.Profile')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corruptions', to='accounts.School')),
            ],
        ),
    ]
