# Generated by Django 2.0.1 on 2019-01-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_corruption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.RemoveField(
            model_name='school',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='school',
            name='students',
        ),
        migrations.RemoveField(
            model_name='school',
            name='treners',
        ),
        migrations.AlterField(
            model_name='corruption',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corruptions', to='schools.School'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
