# Generated by Django 2.2.5 on 2020-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200519_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='skill',
            name='payment_filter',
            field=models.TextField(blank=True, default='all', null=True),
        ),
    ]
