# Generated by Django 2.0.1 on 2019-01-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190121_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-coins', 'first_name']},
        ),
    ]
