# Generated by Django 2.2.5 on 2020-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200523_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='crm_subject2',
            new_name='filter_subject2',
        ),
    ]
