# Generated by Django 2.2.5 on 2020-05-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200527_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='filter_subject2',
            new_name='filter_subject',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_subject',
        ),
    ]
