# Generated by Django 2.2.5 on 2020-05-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200527_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='filter_subject',
            new_name='filter_subject_category',
        ),
    ]
