# Generated by Django 2.0.1 on 2019-02-08 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190127_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hisshedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
