# Generated by Django 2.2.5 on 2020-05-27 21:40

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200527_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='crm_age_connect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crm_level_connect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crm_subject_connect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='filter_teacher_connect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='confirmation_time',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_office2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='crm_show_free_cards',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='filter_subject_category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='hint_numbers',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='need_actions',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='notifications_number',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='payment_filter',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tag_ids',
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='accounts.Profile'),
        ),
    ]
