# Generated by Django 2.0.1 on 2019-02-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_hisshedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hisshedule',
            new_name='hisschedule',
        ),
    ]
