# Generated by Django 2.2.5 on 2020-06-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200527_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications_number',
        ),
    ]
