# Generated by Django 2.2.5 on 2020-06-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_profile_notifications_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_mails', to='accounts.Profile')),
                ('card', models.ManyToManyField(related_name='big_mails', to='accounts.CRMCard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
