# Generated by Django 2.2.5 on 2020-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_bigmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
