# Generated by Django 2.0.1 on 2019-02-08 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190208_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hisschedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None), default=[], size=None),
        ),
    ]
