# Generated by Django 2.2.5 on 2020-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_crmcard_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmcard',
            old_name='dates',
            new_name='birthday',
        ),
    ]
