# Generated by Django 2.2.5 on 2020-07-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200618_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['is_student', 'id']},
        ),
    ]
