# Generated by Django 2.2.5 on 2020-08-05 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200724_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tag_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
