# Generated by Django 2.2.5 on 2020-08-30 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_skill_tag_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_end_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_work',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
