# Generated by Django 2.2.5 on 2020-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200830_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_work',
            field=models.DateTimeField(null=True),
        ),
    ]
