# Generated by Django 2.2.5 on 2020-09-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200830_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['is_student', 'check_end_work', 'id']},
        ),
    ]
