# Generated by Django 2.2.5 on 2020-09-15 00:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200913_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='videohints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
