# Generated by Django 2.0.1 on 2019-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20190208_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileScheduleLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('subject', models.TextField(default='')),
                ('squad_id', models.IntegerField(default=0)),
                ('color', models.TextField(default='')),
                ('teacher', models.TextField(default='')),
                ('cabinet', models.TextField(default='')),
            ],
            options={
                'ordering': ['x', 'y', 'subject'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hisschedule',
        ),
        migrations.AddField(
            model_name='profile',
            name='hisschedule',
            field=models.ManyToManyField(related_name='owner', to='accounts.ProfileScheduleLecture'),
        ),
    ]
