# Generated by Django 2.0.1 on 2019-02-09 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190209_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileschedulelecture',
            options={'ordering': ['x', 'y']},
        ),
        migrations.RemoveField(
            model_name='profileschedulelecture',
            name='squad_id',
        ),
        migrations.AddField(
            model_name='profileschedulelecture',
            name='squad',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulelecture',
            name='cabinet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulelecture',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulelecture',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulelecture',
            name='teacher',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
