# Generated by Django 2.0.1 on 2019-02-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20190209_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileScheduleLecture',
            new_name='ProfileScheduleCell',
        ),
        migrations.RenameField(
            model_name='profileschedulecell',
            old_name='cabinet',
            new_name='cabinets',
        ),
        migrations.RenameField(
            model_name='profileschedulecell',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='profileschedulecell',
            old_name='squad',
            new_name='squads',
        ),
        migrations.RenameField(
            model_name='profileschedulecell',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='profileschedulecell',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
