# Generated by Django 2.0.1 on 2019-02-09 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190209_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileschedulecell',
            options={'ordering': ['y', 'x']},
        ),
        migrations.AddField(
            model_name='profileschedulecell',
            name='indexes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
