# Generated by Django 2.1.7 on 2019-02-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20190209_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaiavka',
            old_name='name',
            new_name='first_name',
        ),
    ]
