# Generated by Django 2.1.7 on 2019-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20190216_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaiavka',
            name='mail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='zaiavka',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
