# Generated by Django 2.1.7 on 2019-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190217_1514'),
        ('accounts', '0039_auto_20190216_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='profile',
            name='schools',
            field=models.ManyToManyField(related_name='people', to='schools.School'),
        ),
    ]
