# Generated by Django 2.1.7 on 2019-02-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190217_1514'),
        ('accounts', '0040_auto_20190217_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaiavka',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zaiavkas', to='schools.School'),
        ),
    ]
