# Generated by Django 2.1.7 on 2019-02-20 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190220_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_ceo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_trener',
        ),
        migrations.AddField(
            model_name='profession',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profession',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(related_name='workers', to='accounts.Profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='easy_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hard_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='cabinets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='indexes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='squads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profileschedulecell',
            name='teachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
