# Generated by Django 2.1.7 on 2019-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20190220_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
