# Generated by Django 2.1.7 on 2019-02-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_profile_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hisschedule',
        ),
        migrations.DeleteModel(
            name='ProfileScheduleCell',
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_categories', to='accounts.Profession'),
        ),
    ]
