# Generated by Django 2.1.7 on 2019-02-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20190223_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_categories',
            field=models.ManyToManyField(related_name='job_workers', to='accounts.JobCategory'),
        ),
    ]
