# Generated by Django 2.1.7 on 2019-02-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20190227_0647'),
        ('accounts', '0047_auto_20190226_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crm_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crm_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.Office'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crm_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.SubjectCategory'),
        ),
    ]
