# Generated by Django 2.1.7 on 2019-03-07 17:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_misslesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='misslesson',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='misslesson',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miss_lessons', to='accounts.Profile'),
        ),
    ]
