# Generated by Django 2.1.7 on 2019-03-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190307_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misslesson',
            old_name='title',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='misslesson',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
