# Generated by Django 2.1.7 on 2019-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20190307_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='salary',
            new_name='money',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
