# Generated by Django 2.1.7 on 2019-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_profile_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
