# Generated by Django 2.1.7 on 2019-04-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190407_1713'),
        ('accounts', '0055_auto_20190312_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_author', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CRMColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number_of_cards', models.IntegerField(default=0)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_columns', to='schools.School')),
            ],
        ),
        migrations.AddField(
            model_name='crmcard',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.CRMColumn'),
        ),
    ]
