# Generated by Django 2.1.7 on 2019-04-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190407_1713'),
        ('accounts', '0056_auto_20190407_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcolumn',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='crmcard',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_cards', to='schools.School'),
        ),
    ]
