# Generated by Django 2.1.7 on 2019-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20190407_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
