# Generated by Django 2.1.7 on 2019-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_crmcard_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hint',
            field=models.IntegerField(default=0),
        ),
    ]
