# Generated by Django 2.1.7 on 2019-04-25 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_profile_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hint',
        ),
        migrations.AddField(
            model_name='profile',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0], size=None),
        ),
    ]
