# Generated by Django 2.1.7 on 2019-04-26 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20190425_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0, 0, 0], size=None),
        ),
    ]
