# Generated by Django 2.1.7 on 2019-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190407_1713'),
        ('accounts', '0063_auto_20190426_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crm_age_connect',
            field=models.ManyToManyField(default=1, related_name='students', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crm_subject_connect',
            field=models.ManyToManyField(default=1, related_name='students', to='schools.SubjectCategory'),
        ),
    ]
