# Generated by Django 2.1.7 on 2019-05-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20190427_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcard',
            options={'ordering': ['saved', 'timestamp']},
        ),
    ]
