# Generated by Django 2.1.7 on 2019-05-18 20:53

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190507_2111'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, default='name', null=True),
        ),
    ]
