# Generated by Django 2.1.7 on 2019-05-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20190518_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oldcolumn', models.CharField(max_length=250)),
                ('newcolumn', models.CharField(max_length=250)),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_histories', to='accounts.Profile')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.CRMCard')),
            ],
        ),
    ]
