# Generated by Django 2.1.7 on 2019-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_crmcardhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcardhistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='crmcolumn',
            name='number_of_cards',
        ),
        migrations.AddField(
            model_name='crmcardhistory',
            name='edit',
            field=models.TextField(default=''),
        ),
    ]
