# Generated by Django 2.1.7 on 2019-05-20 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20190520_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcardhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='crmcard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to='accounts.Profile'),
        ),
    ]
