# Generated by Django 2.1.7 on 2019-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_money'),
        ('accounts', '0069_auto_20190520_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmcolumn',
            name='school',
        ),
        migrations.AddField(
            model_name='crmcolumn',
            name='schools',
            field=models.ManyToManyField(related_name='crm_columns', to='schools.School'),
        ),
    ]
