# Generated by Django 2.1.7 on 2019-05-24 03:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20190521_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('easy_skills', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('middle_skills', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('hard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('pro_skills', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('crm_show_free_cards', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='easy_skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hard_skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middle_skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pro_skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag_ids',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.Skill'),
        ),
    ]
