# Generated by Django 2.2.1 on 2019-05-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_money'),
        ('accounts', '0071_auto_20190524_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('itstype', models.CharField(max_length=25)),
                ('author_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_notifications', to='accounts.Profile')),
                ('profession', models.ManyToManyField(related_name='notifications', to='accounts.Profession')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.School')),
            ],
        ),
    ]
