# Generated by Django 2.2.1 on 2019-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
