# Generated by Django 2.2.1 on 2019-05-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_number',
            field=models.IntegerField(default=0),
        ),
    ]
