# Generated by Django 2.2.1 on 2019-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_auto_20190529_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='was_called',
            field=models.BooleanField(default=False),
        ),
    ]
