# Generated by Django 2.2.1 on 2019-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_crmcard_was_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='need_actions',
            field=models.IntegerField(default=0),
        ),
    ]
