# Generated by Django 2.2.1 on 2019-06-02 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='days_of_weeks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=None),
        ),
    ]
