# Generated by Django 2.2.1 on 2019-06-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_crmcard_days_of_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='action',
            field=models.CharField(default='', max_length=250),
        ),
    ]
