# Generated by Django 2.2.1 on 2019-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_money'),
        ('accounts', '0082_crmcard_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='hashtags', to='schools.School')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
