# Generated by Django 2.2.1 on 2019-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='hashtags',
            field=models.ManyToManyField(related_name='cards', to='accounts.Hashtag'),
        ),
    ]
