# Generated by Django 2.2.1 on 2019-06-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_auto_20190611_1530'),
        ('accounts', '0085_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_categories', to='schools.School'),
        ),
        migrations.AddField(
            model_name='profession',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='schools.School'),
        ),
    ]
