# Generated by Django 2.2.1 on 2019-06-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_auto_20190611_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='school',
        ),
    ]
