# Generated by Django 2.2.1 on 2019-06-23 10:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_auto_20190623_1055'),
        ('accounts', '0087_auto_20190612_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crm_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crm_office',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crm_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hint_numbers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications_number',
        ),
        migrations.AddField(
            model_name='skill',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_age2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by2', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.Office'),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_office2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by2', to='schools.Office'),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='crm_subject2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by2', to='schools.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='hint_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0, 0, 0, 0], size=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='notifications_number',
            field=models.IntegerField(default=0),
        ),
    ]
