# Generated by Django 2.2.1 on 2019-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20190623_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='skill',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
