# Generated by Django 2.2.1 on 2019-06-28 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_auto_20190627_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='confirmation_code',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='confirmation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
