# Generated by Django 2.2.1 on 2019-06-28 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20190628_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='confirmation_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
