# Generated by Django 2.2.1 on 2019-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20190628_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='confirmation_code',
            field=models.CharField(default='', max_length=250),
        ),
    ]
