# Generated by Django 2.2.1 on 2019-07-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_auto_20190702_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='to_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_reviews', to='accounts.Profile'),
        ),
    ]
