# Generated by Django 2.2.1 on 2019-07-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_auto_20190702_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.TextField(default='', null=True),
        ),
    ]
