# Generated by Django 2.2.1 on 2019-07-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_auto_20190706_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcard',
            name='card_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='accounts.Profile'),
        ),
    ]
