# Generated by Django 2.2.1 on 2019-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20190708_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='last_groups',
            field=models.IntegerField(default=-1),
        ),
    ]
