# Generated by Django 2.2.1 on 2019-07-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_crmcard_last_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcard',
            name='card_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='accounts.Profile'),
        ),
    ]
