# Generated by Django 2.2.1 on 2019-07-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_auto_20190708_1559'),
        ('accounts', '0098_auto_20190708_2132'),
    ]

    operations = [
    ]
