# Generated by Django 2.2.1 on 2019-07-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_merge_20190709_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmcard',
            options={'ordering': ['saved', '-timestamp']},
        ),
    ]
