# Generated by Django 2.2.1 on 2019-07-20 11:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_auto_20190719_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='card_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='card_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='crmcard',
            name='card_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='accounts.Profile'),
        ),
    ]
