# Generated by Django 2.2.1 on 2019-07-20 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_auto_20190720_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='card_ids',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='card_numbers',
        ),
        migrations.AddField(
            model_name='crmcard',
            name='hashtag_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='crmcard',
            name='hashtag_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
    ]
