# Generated by Django 2.2.1 on 2019-07-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0033_school_money_month'),
        ('accounts', '0102_auto_20190720_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='schools.School'),
        ),
    ]
