# Generated by Django 2.2.1 on 2019-08-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_paymenthistory_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaiavka',
            name='school',
        ),
        migrations.DeleteModel(
            name='Corruption',
        ),
        migrations.DeleteModel(
            name='Zaiavka',
        ),
    ]
