# Generated by Django 2.2.1 on 2019-08-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_auto_20190803_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='extra_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
