# Generated by Django 2.2.1 on 2019-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_auto_20190803_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='premoney',
            field=models.IntegerField(default=0),
        ),
    ]
