# Generated by Django 2.2.4 on 2019-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('accounts', '0106_crmcard_premoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crm_level_connect',
            field=models.ManyToManyField(default=1, related_name='students', to='schools.SubjectLevel'),
        ),
    ]
