# Generated by Django 2.2.5 on 2019-09-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_profile_crm_level_connect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['-title']},
        ),
    ]
