# Generated by Django 2.2.5 on 2019-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_auto_20190920_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id', '-coins', 'first_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.TextField(default='', null=True),
        ),
    ]
