# Generated by Django 2.2.5 on 2019-09-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20190921_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcard',
            name='colour',
            field=models.CharField(default='white', max_length=250),
        ),
    ]
