# Generated by Django 2.2.5 on 2019-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_crmcard_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crm_level_connect',
            field=models.ManyToManyField(default=2, related_name='students', to='schools.SubjectLevel'),
        ),
    ]
