# Generated by Django 2.2.5 on 2019-10-08 10:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_delete_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='filter_teacher_connect',
            field=models.ManyToManyField(related_name='filter_teacher', to='accounts.Skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location),
        ),
    ]
