# Generated by Django 2.2.5 on 2019-10-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_auto_20191008_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='hint_numbers',
        ),
    ]
