# Generated by Django 2.2.5 on 2019-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_remove_skill_hint_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
