# Generated by Django 2.2.5 on 2019-10-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('accounts', '0115_auto_20191018_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmcard',
            name='hashtag_ids',
        ),
        migrations.RemoveField(
            model_name='crmcard',
            name='hashtag_numbers',
        ),
        migrations.AddField(
            model_name='skill',
            name='interested_subjects',
            field=models.ManyToManyField(default=1, related_name='interested_students', to='schools.SubjectCategory'),
        ),
    ]
