# Generated by Django 2.2.5 on 2019-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('accounts', '0116_auto_20191021_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='schools',
            field=models.ManyToManyField(related_name='job_categories', to='schools.School'),
        ),
    ]
