# Generated by Django 2.2.5 on 2019-10-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('accounts', '0117_jobcategory_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='crm_cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.Cabinet'),
        ),
    ]
