# Generated by Django 2.0.1 on 2018-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('cost', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
