# Generated by Django 2.0.1 on 2018-11-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
