# Generated by Django 2.0.1 on 2019-02-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_auto_20190127_0915'),
        ('documents', '0001_initial'),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='files',
            field=models.ManyToManyField(related_name='docfolder', to='todolist.Document'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docchilds', to='documents.DocumentFolder'),
        ),
        migrations.AddField(
            model_name='documentcache',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doccache', to='accounts.Profile'),
        ),
    ]
