# Generated by Django 2.0.1 on 2019-02-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfolder',
            old_name='lesson_list',
            new_name='files',
        ),
    ]
