# Generated by Django 2.2.5 on 2019-10-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentfolder_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfolder',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_docfolders', to='schools.School'),
        ),
    ]
