# Generated by Django 2.0.1 on 2018-11-22 08:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_ans', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None)),
                ('solver_correctness', models.BooleanField(default=False)),
                ('solver_try_number', models.IntegerField(default=0)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tasks.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None)),
                ('cost', models.IntegerField(default=1)),
                ('is_test', models.BooleanField(default=False)),
                ('is_mult_ans', models.BooleanField(default=False)),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Task')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='solver',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tasks.Task'),
        ),
    ]
