# Generated by Django 2.2.5 on 2019-11-07 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=tasks.models.upload_location)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('cost', models.IntegerField(default=1)),
                ('is_test', models.BooleanField(default=False)),
                ('is_mult_ans', models.BooleanField(default=False)),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('tags', models.ManyToManyField(related_name='tasks', to='tasks.ProblemTag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_ans', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('solver_correctness', models.BooleanField(default=False)),
                ('solver_try_number', models.IntegerField(default=0)),
                ('author_profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='check_tasks', to='accounts.Profile')),
                ('task', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solver_checks', to='tasks.Task')),
            ],
        ),
    ]
