# Generated by Django 2.0.1 on 2018-12-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181202_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solver',
            name='author_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='check_tasks', to='accounts.Profile'),
        ),
    ]
