# Generated by Django 2.2.5 on 2020-08-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200802_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer_type',
        ),
    ]
