# Generated by Django 2.0.1 on 2019-01-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20181217_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['cost']},
        ),
    ]
