# Generated by Django 2.1.7 on 2019-02-27 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190217_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solver',
            name='solver_ans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
