# Generated by Django 2.2.5 on 2019-10-08 10:25

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190227_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='task',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.upload_location),
        ),
    ]
