# Generated by Django 2.2.5 on 2019-11-07 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to=schools.models.upload_location)),
                ('content', models.TextField(default='')),
                ('slogan', models.CharField(default='', max_length=250)),
                ('site', models.CharField(default='', max_length=250)),
                ('worktime', models.CharField(default='', max_length=250)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('social_networks', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('social_network_links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('offices', models.IntegerField(default=0)),
                ('average_cost', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('version', models.CharField(default='', max_length=10)),
                ('sms_amount', models.IntegerField(default=0)),
                ('pay_day_diff', models.IntegerField(default=5)),
                ('schedule_type', models.CharField(default='', max_length=10)),
                ('schedule_interval', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ['version', 'rating', '-average_cost'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='school_subject_levels', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('school_categories', models.ManyToManyField(related_name='subject_categories', to='schools.SchoolCategory')),
                ('schools', models.ManyToManyField(related_name='school_subject_categories', to='schools.School')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='school_subject_ages', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFilterOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('filter_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', to='schools.SchoolFilter')),
                ('schools', models.ManyToManyField(related_name='filter_options', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='main_filters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcategories', to='schools.SchoolFilter'),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='schools',
            field=models.ManyToManyField(related_name='categories', to='schools.School'),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='second_filters',
            field=models.ManyToManyField(related_name='categories', to='schools.SchoolFilter'),
        ),
        migrations.CreateModel(
            name='SchoolBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to=schools.models.upload_location)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('latitude', models.CharField(default='0.0', max_length=250)),
                ('longtude', models.CharField(default='0.0', max_length=250)),
                ('address', models.TextField(default='')),
                ('region', models.CharField(default='', max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_offices', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MoneyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_object', to='schools.School')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MoneyMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('money_spend', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('money_earn', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_months', to='schools.School')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FilterControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='filter_control', to='schools.SubjectCategory')),
                ('levels', models.ManyToManyField(related_name='filter_control', to='schools.SubjectLevel')),
            ],
        ),
        migrations.CreateModel(
            name='ElliteSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.ManyToManyField(related_name='elite_list', to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='schools.Office')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
