# Generated by Django 2.0.1 on 2019-01-04 02:01

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_profile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=schools.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('image_banner', models.ImageField(blank=True, height_field='height_field2', null=True, upload_to=schools.models.upload_location, width_field='width_field2')),
                ('height_field2', models.IntegerField(default=0, null=True)),
                ('width_field2', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(default='')),
                ('slogan', models.CharField(default='', max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('curator', models.ManyToManyField(default=1, related_name='school_curator', to='accounts.Profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
