# Generated by Django 2.0.1 on 2019-01-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='curator',
        ),
    ]
