# Generated by Django 2.2.5 on 2020-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200102_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schedule_type',
            field=models.CharField(default='classic', max_length=10),
        ),
    ]
