# Generated by Django 2.1.7 on 2019-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='new_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='official_school',
            field=models.BooleanField(default=False),
        ),
    ]
