# Generated by Django 2.2.5 on 2020-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200207_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='')),
                ('address', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
