# Generated by Django 2.2.5 on 2020-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_helpvideos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpvideos',
            old_name='address',
            new_name='title',
        ),
    ]
