# Generated by Django 2.1.7 on 2019-02-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_ages', to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_categories', to='schools.School')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_cabinets', to='schools.School'),
        ),
    ]
