# Generated by Django 2.1.7 on 2019-02-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20190227_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinett',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_cabinets', to='schools.School')),
            ],
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='school',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
