# Generated by Django 2.2.5 on 2020-03-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200217_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['importance', 'version', 'rating', '-average_cost']},
        ),
        migrations.AddField(
            model_name='school',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
