# Generated by Django 2.1.7 on 2019-02-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190227_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.TextField(default='')),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.AddField(
            model_name='office',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_offices', to='schools.School'),
        ),
    ]
