# Generated by Django 2.2.5 on 2020-03-17 22:25

from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200315_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to=schools.models.upload_location)),
                ('content', models.TextField(default='')),
                ('link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(default='')),
                ('user_id', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialmedias', to='schools.School')),
                ('socialmedia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='schools.SocialMedia')),
            ],
        ),
    ]
