# Generated by Django 2.2.5 on 2020-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_socialmedia_socialmediaaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpvideos',
            name='href',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='server',
            field=models.TextField(default=''),
        ),
    ]
