# Generated by Django 2.1.7 on 2019-03-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0052_auto_20190228_1132'),
        ('schools', '0007_auto_20190227_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabinett',
            new_name='Cabinet',
        ),
    ]
