# Generated by Django 2.2.5 on 2020-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20200323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpvideos',
            name='video',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
