# Generated by Django 2.1.7 on 2019-04-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20190301_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_cabinets', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='office',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_offices', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='subjectage',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_ages', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject_categories', to='schools.School'),
        ),
    ]
