# Generated by Django 2.1.7 on 2019-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190407_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
