# Generated by Django 2.2.5 on 2020-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20200323_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='groupid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='groupname',
            field=models.TextField(default=''),
        ),
    ]
