# Generated by Django 2.2.5 on 2020-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20200325_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='first_connect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='group_access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='secretkey',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='serverid',
            field=models.TextField(default=''),
        ),
    ]
