# Generated by Django 2.2.1 on 2019-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='new_schedule',
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='longtude',
            field=models.FloatField(default=0),
        ),
    ]
