# Generated by Django 2.2.5 on 2020-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20200325_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='confirmation_code',
            field=models.TextField(default=''),
        ),
    ]
