# Generated by Django 2.2.1 on 2019-06-08 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20190608_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='official_school',
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='school',
            name='offices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='social_networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='school',
            name='worktime',
            field=models.CharField(default='', max_length=250),
        ),
    ]
