# Generated by Django 2.2.1 on 2019-06-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20190608_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.CharField(default='0.0', max_length=250),
        ),
        migrations.AlterField(
            model_name='school',
            name='longtude',
            field=models.CharField(default='0.0', max_length=250),
        ),
    ]
