# Generated by Django 2.2.5 on 2020-05-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_socialmediaaccount_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='cities', to='schools.School')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
