# Generated by Django 2.2.5 on 2020-05-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectage',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='subjectlevel',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='city',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='school',
            name='offices',
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='schools.City'),
        ),
        migrations.DeleteModel(
            name='FilterControl',
        ),
    ]
