# Generated by Django 2.2.1 on 2019-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20190608_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('profession', models.ManyToManyField(related_name='elite', to='schools.School')),
            ],
        ),
    ]
