# Generated by Django 2.2.1 on 2019-06-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_eliteschools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eliteschools',
            name='title',
        ),
    ]
