# Generated by Django 2.2.5 on 2020-05-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200527_2140'),
        ('squads', '0018_auto_20200527_2140'),
        ('subjects', '0019_auto_20200527_2140'),
        ('schools', '0014_auto_20200527_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectAge',
        ),
        migrations.DeleteModel(
            name='SubjectLevel',
        ),
    ]
