# Generated by Django 2.2.1 on 2019-06-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_remove_eliteschools_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteschools',
            old_name='profession',
            new_name='schools',
        ),
    ]
