# Generated by Django 2.2.5 on 2020-05-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20200527_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='schools',
            field=models.ManyToManyField(related_name='cities', to='schools.School'),
        ),
    ]
