# Generated by Django 2.2.1 on 2019-06-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20190610_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id']},
        ),
    ]
