# Generated by Django 2.2.5 on 2020-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20200528_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bill_day_diff',
            field=models.IntegerField(default=5),
        ),
    ]
