# Generated by Django 2.2.1 on 2019-06-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_auto_20190611_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectage',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subjectcategory',
            name='school',
        ),
        migrations.AddField(
            model_name='subjectage',
            name='schools',
            field=models.ManyToManyField(related_name='school_subject_ages', to='schools.School'),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='schools',
            field=models.ManyToManyField(related_name='school_subject_categories', to='schools.School'),
        ),
    ]
