# Generated by Django 2.2.5 on 2020-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_bill_day_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('schools', models.ManyToManyField(related_name='mail_templates', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
