# Generated by Django 2.2.5 on 2020-06-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_mailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='schools',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_templates', to='schools.School'),
        ),
    ]
