# Generated by Django 2.2.1 on 2019-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20190612_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='average_cost',
            field=models.IntegerField(default=0),
        ),
    ]
