# Generated by Django 2.2.1 on 2019-06-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_school_average_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['rating']},
        ),
    ]
