# Generated by Django 2.2.5 on 2020-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_auto_20200624_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['-usability']},
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
