# Generated by Django 2.2.1 on 2019-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_auto_20190623_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longtude',
        ),
        migrations.AddField(
            model_name='office',
            name='latitude',
            field=models.CharField(default='0.0', max_length=250),
        ),
        migrations.AddField(
            model_name='office',
            name='longtude',
            field=models.CharField(default='0.0', max_length=250),
        ),
        migrations.AddField(
            model_name='office',
            name='region',
            field=models.CharField(default='', max_length=250),
        ),
    ]
