# Generated by Django 2.2.5 on 2020-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_auto_20200624_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
