# Generated by Django 2.2.5 on 2020-06-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_mailtemplate_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='usability',
        ),
    ]
