# Generated by Django 2.2.1 on 2019-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20190623_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='site',
            field=models.CharField(default='', max_length=250),
        ),
    ]
