# Generated by Django 2.2.1 on 2019-06-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_school_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subjectage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cabinet',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='schools.Office'),
        ),
    ]
