# Generated by Django 2.2.5 on 2020-08-13 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20200812_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
