# Generated by Django 2.2.1 on 2019-06-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20190629_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='schools.School'),
        ),
    ]
