# Generated by Django 2.2.1 on 2019-07-03 07:59

from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20190629_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='height_field2',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image_banner',
        ),
        migrations.RemoveField(
            model_name='school',
            name='width_field2',
        ),
        migrations.CreateModel(
            name='SchoolBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, height_field='height_field2', null=True, upload_to=schools.models.upload_location, width_field='width_field2')),
                ('height_field2', models.IntegerField(default=0, null=True)),
                ('width_field2', models.IntegerField(default=0, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='schools.School')),
            ],
        ),
    ]
