# Generated by Django 2.2.5 on 2020-08-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_school_money_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='schedule_type',
        ),
        migrations.CreateModel(
            name='SubscribePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('transactionId', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_payments', to='schools.School')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
