# Generated by Django 2.2.1 on 2019-07-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_auto_20190703_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['id']},
        ),
    ]
