# Generated by Django 2.2.1 on 2019-07-06 04:32

import django.contrib.postgres.fields
from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_auto_20190706_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image_album',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=schools.models.upload_location, width_field='width_field'), default=list, size=None),
        ),
    ]
