# Generated by Django 2.2.5 on 2020-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_auto_20200823_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tried_free',
            field=models.BooleanField(default=False),
        ),
    ]
