# Generated by Django 2.2.1 on 2019-07-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_school_image_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image_album',
        ),
    ]
