# Generated by Django 2.2.1 on 2019-07-07 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_remove_school_image_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbanner',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='school',
            name='social_networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None),
        ),
    ]
