# Generated by Django 2.2.1 on 2019-07-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_auto_20190707_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_obejct', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
