# Generated by Django 2.2.1 on 2019-07-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_moneyobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyobject',
            options={'ordering': ['-id']},
        ),
    ]
