# Generated by Django 2.2.1 on 2019-07-21 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_auto_20190720_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money_earnn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='school',
            name='money_spendd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
