# Generated by Django 2.2.1 on 2019-07-21 21:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_auto_20190721_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money_month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
