# Generated by Django 2.2.1 on 2019-07-22 04:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0033_school_money_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money_spend2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
