# Generated by Django 2.2.1 on 2019-07-22 04:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_school_money_spend2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='money_spend2',
        ),
        migrations.AlterField(
            model_name='school',
            name='money_earnn',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='school',
            name='money_spendd',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=list, size=None),
        ),
    ]
