# Generated by Django 2.2.1 on 2019-08-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_auto_20190722_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='elite', to='schools.School')),
            ],
        ),
        migrations.DeleteModel(
            name='EliteSchools',
        ),
    ]
