# Generated by Django 2.2.1 on 2019-08-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0036_auto_20190812_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolversion',
            name='schools',
            field=models.ManyToManyField(related_name='versions', to='schools.School'),
        ),
    ]
