# Generated by Django 2.2.1 on 2019-08-14 00:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_auto_20190813_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=250)),
                ('money_spend', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('money_earn', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='money_earnn',
        ),
        migrations.RemoveField(
            model_name='school',
            name='money_month',
        ),
        migrations.RemoveField(
            model_name='school',
            name='money_spendd',
        ),
        migrations.AddField(
            model_name='school',
            name='social_network_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='school',
            name='version',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='social_networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='SchoolVersion',
        ),
        migrations.AddField(
            model_name='moneymonth',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_months', to='schools.School'),
        ),
    ]
