# Generated by Django 2.2.4 on 2019-08-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_auto_20190814_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneymonth',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneyobject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_object', to='schools.School'),
        ),
    ]
