# Generated by Django 2.2.4 on 2019-08-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_auto_20190830_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['rating', 'version', '-average_cost']},
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='school_subject_levels', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
