# Generated by Django 2.2.4 on 2019-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='FilterControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='filter_control', to='schools.SubjectCategory')),
                ('levels', models.ManyToManyField(related_name='filter_control', to='schools.SubjectLevel')),
            ],
        ),
    ]
