# Generated by Django 2.2.5 on 2019-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0041_auto_20190902_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sms_amount',
            field=models.IntegerField(default=0),
        ),
    ]
