# Generated by Django 2.2.5 on 2019-09-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_school_sms_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='pay_day_diff',
            field=models.IntegerField(default=5),
        ),
    ]
