# Generated by Django 2.2.5 on 2019-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_school_pay_day_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schedule_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
