# Generated by Django 2.2.5 on 2019-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0044_school_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schedule_interval',
            field=models.IntegerField(default=60),
        ),
    ]
