# Generated by Django 2.2.5 on 2019-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0045_school_schedule_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['version', 'rating', '-average_cost']},
        ),
    ]
