# Generated by Django 2.2.5 on 2019-10-08 10:25

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_auto_20191008_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='school',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='schoolbanner',
            name='height_field2',
        ),
        migrations.RemoveField(
            model_name='schoolbanner',
            name='width_field2',
        ),
        migrations.AlterField(
            model_name='school',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.upload_location),
        ),
        migrations.AlterField(
            model_name='schoolbanner',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.upload_location),
        ),
    ]
