# Generated by Django 2.2.5 on 2019-10-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_auto_20191008_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElliteSchools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.ManyToManyField(related_name='elite_list', to='schools.School')),
            ],
        ),
    ]
