# Generated by Django 2.2.5 on 2019-10-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0048_elliteschools'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.IntegerField(default=1)),
                ('schools', models.ManyToManyField(related_name='categories', to='schools.School')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
