# Generated by Django 2.2.5 on 2019-10-10 04:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0049_schoolcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('schools', models.ManyToManyField(related_name='filters', to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFilterOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('second_filters', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('filter_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', to='schools.SchoolFilter')),
                ('schools', models.ManyToManyField(related_name='filter_options', to='schools.School')),
            ],
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='main_filters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcategories', to='schools.SchoolFilter'),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='second_filters',
            field=models.ManyToManyField(related_name='categories', to='schools.SchoolFilter'),
        ),
    ]
