# Generated by Django 2.2.5 on 2019-10-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0050_auto_20191010_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfilter',
            name='schools',
        ),
    ]
