# Generated by Django 2.2.5 on 2019-10-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0051_remove_schoolfilter_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfilteroption',
            name='second_filters',
        ),
    ]
