# Generated by Django 2.2.5 on 2019-10-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0052_remove_schoolfilteroption_second_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolcategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='schoolfilteroption',
            options={'ordering': ['id']},
        ),
    ]
