# Generated by Django 2.2.5 on 2019-10-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0053_auto_20191011_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolcategory',
            options={'ordering': ['number']},
        ),
    ]
