# Generated by Django 2.2.5 on 2019-10-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0054_auto_20191013_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcategory',
            name='school_categories',
            field=models.ManyToManyField(related_name='subject_categories', to='schools.SchoolCategory'),
        ),
    ]
