# Generated by Django 2.2.5 on 2019-10-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0055_subjectcategory_school_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfilter',
            options={'ordering': ['id']},
        ),
    ]
