# Generated by Django 2.0.1 on 2018-11-22 08:20

from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.Cell')),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squad_lectures', to='squads.Squad')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=subjects.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('content', models.TextField()),
                ('slogan', models.CharField(default='', max_length=250)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('squads', models.ManyToManyField(default=1, related_name='subjects', to='squads.Squad')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_subjects', to='accounts.Profile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('subjects', models.ManyToManyField(default=1, related_name='subject_categories', to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(default='')),
                ('end', models.TextField(default='')),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lectures', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='cell',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_cell', to='subjects.Day'),
        ),
        migrations.AddField(
            model_name='cell',
            name='time_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_cell', to='subjects.TimePeriod'),
        ),
    ]
