# Generated by Django 2.2.5 on 2019-11-07 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squads', '0001_initial'),
        ('papers', '0001_initial'),
        ('schools', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['day', 'time_period'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, null=True)),
                ('cost_period', models.CharField(default='month', max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location)),
                ('start_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), default=list, size=None)),
                ('squad_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None)),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location)),
                ('image_back', models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location)),
                ('color_back', models.TextField(default='')),
                ('content', models.TextField()),
                ('slogan', models.CharField(default='', max_length=250)),
                ('number_of_materials', models.IntegerField(default=0, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_public_cost', models.BooleanField(default=True)),
                ('age', models.ManyToManyField(related_name='age_subjects', to='schools.SubjectAge')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_subjects', to='accounts.Profile')),
                ('category', models.ManyToManyField(related_name='category_subjects', to='schools.SubjectCategory')),
                ('filter_course_connect', models.ManyToManyField(related_name='filter_course_connect', to='accounts.Skill')),
                ('filter_options', models.ManyToManyField(related_name='subjects', to='schools.SchoolFilterOption')),
                ('level', models.ManyToManyField(related_name='level_subjects', to='schools.SubjectLevel')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='schools.School')),
                ('squads', models.ManyToManyField(related_name='subjects', to='squads.Squad')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(default='')),
                ('end', models.TextField(default='')),
                ('num', models.IntegerField(default=0)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_periods', to='schools.School')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('done_by', models.ManyToManyField(related_name='done_subject_materials', to='accounts.Profile')),
                ('lessons', models.ManyToManyField(related_name='subject_materials', to='papers.Lesson')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_materials', to='schools.School')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.Subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit', models.TextField(default='')),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_histories', to='accounts.Profile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_histories', to='subjects.Subject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('person_number', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('age', models.ManyToManyField(related_name='age_lectures', to='schools.SubjectAge')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_lecture', to='schools.Cabinet')),
                ('category', models.ManyToManyField(related_name='category_lectures', to='schools.SubjectCategory')),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.Cell')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.Day')),
                ('level', models.ManyToManyField(related_name='level_lectures', to='schools.SubjectLevel')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_lectures', to='schools.Office')),
                ('people', models.ManyToManyField(related_name='hislectures', to='accounts.Profile')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_lectures', to='schools.School')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_lectures', to='squads.Squad')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lectures', to='subjects.Subject')),
            ],
            options={
                'ordering': ['cell'],
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_cell', to='subjects.Day'),
        ),
        migrations.AddField(
            model_name='cell',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_cells', to='schools.School'),
        ),
        migrations.AddField(
            model_name='cell',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_cell', to='subjects.TimePeriod'),
        ),
        migrations.CreateModel(
            name='CacheAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiscache', to='accounts.Profile')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='squads.Squad')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.TextField(default='')),
                ('grade', models.IntegerField(default=-1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_attendances', to='schools.School')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_attendances', to='squads.Squad')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hisgrades', to='accounts.Profile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendances', to='subjects.Subject')),
                ('subject_materials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_atts', to='subjects.SubjectMaterials')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madegrades', to='accounts.Profile')),
            ],
            options={
                'ordering': ['subject_materials', 'squad', 'student'],
            },
        ),
    ]
