# Generated by Django 2.2.5 on 2019-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='public_cost',
            field=models.BooleanField(default=True),
        ),
    ]
