# Generated by Django 2.2.5 on 2019-11-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20191107_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='people',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='person_number',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='school',
        ),
    ]
