# Generated by Django 2.2.5 on 2019-11-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20191111_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaterials',
            name='made',
            field=models.CharField(default='month', max_length=250),
        ),
    ]
