# Generated by Django 2.0.1 on 2018-11-24 17:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20181122_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lesson_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
        ),
    ]
