# Generated by Django 2.2.5 on 2019-12-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20191127_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaterials',
            name='made',
        ),
    ]
