# Generated by Django 2.0.1 on 2018-11-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('subjects', '0004_subject_lesson_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('lessons', models.ManyToManyField(related_name='subject_materials', to='papers.Lesson')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lesson_ids',
        ),
        migrations.AddField(
            model_name='subjectmaterials',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.Subject'),
        ),
    ]
