# Generated by Django 2.2.5 on 2019-12-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20191201_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_public_cost',
        ),
    ]
