# Generated by Django 2.0.1 on 2018-11-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
        ('subjects', '0005_auto_20181125_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='squads.Squad')),
                ('subject_materials', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squad_orders', to='subjects.SubjectMaterials')),
                ('time_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='subjects.TimePeriod')),
            ],
        ),
    ]
