# Generated by Django 2.2.5 on 2019-12-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0012_delete_financeclosed'),
        ('subjects', '0006_auto_20191202_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('money', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('need_money', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_closed', to='squads.NeedMoney')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_closed', to='subjects.Subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
