# Generated by Django 2.0.1 on 2018-11-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_squadorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadorder',
            name='squad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='squadorder',
            name='time_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_period_squad_orders', to='subjects.TimePeriod'),
        ),
    ]
