# Generated by Django 2.0.1 on 2018-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20181125_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
