# Generated by Django 2.2.5 on 2019-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_financeclosed_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeclosed',
            name='start',
            field=models.DateField(),
        ),
    ]
