# Generated by Django 2.0.1 on 2018-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_day_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['day', 'time_period']},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['cell']},
        ),
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'ordering': ['num']},
        ),
        migrations.AlterField(
            model_name='squadorder',
            name='date',
            field=models.DateField(),
        ),
    ]
