# Generated by Django 2.2.5 on 2019-12-10 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20191210_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclosed',
            name='first_present',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
