# Generated by Django 2.0.1 on 2018-11-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20181125_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['-number']},
        ),
    ]
