# Generated by Django 2.0.1 on 2018-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20181125_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadorder',
            options={'ordering': ['subject_materials']},
        ),
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['number']},
        ),
    ]
