# Generated by Django 2.2.5 on 2019-12-13 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_financeclosed_first_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeclosed',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='financeclosed',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='financeclosed',
            name='money',
        ),
        migrations.AddField(
            model_name='financeclosed',
            name='bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financeclosed',
            name='moneys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
    ]
