# Generated by Django 2.0.1 on 2018-11-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_squadweek'),
        ('subjects', '0011_auto_20181125_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='squads.Squad')),
                ('time_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squad_cells', to='subjects.TimePeriod')),
                ('week', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='week_cells', to='squads.SquadWeek')),
            ],
            options={
                'ordering': ['date', 'time_period'],
            },
        ),
        migrations.AddField(
            model_name='squadorder',
            name='squad_cells',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_cell_orders', to='subjects.SquadCell'),
        ),
    ]
