# Generated by Django 2.0.1 on 2018-11-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_auto_20181125_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadcell',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_cells', to='squads.SquadWeek'),
        ),
    ]
