# Generated by Django 2.2.5 on 2019-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_financeclosed_closed_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclosed',
            name='fixed_date',
            field=models.BooleanField(default=False),
        ),
    ]
