# Generated by Django 2.0.1 on 2018-11-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20181126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_cell', to='subjects.Day'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_cell', to='subjects.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.Cell'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_lectures', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lectures', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='squadcell',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='squadcell',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_cells', to='subjects.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='squadorder',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='squadorder',
            name='subject_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_orders', to='subjects.SubjectMaterials'),
        ),
        migrations.AlterField(
            model_name='squadorder',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_period_squad_orders', to='subjects.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='squads',
            field=models.ManyToManyField(null=True, related_name='subjects', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='teachers_subjects', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='subject_categories', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='subjectmaterials',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.Subject'),
        ),
    ]
