# Generated by Django 2.2.5 on 2019-12-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_financeclosed_fixed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeclosed',
            name='fixed_date',
        ),
    ]
