# Generated by Django 2.0.1 on 2018-11-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20181126_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadorder',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='squadorder',
            name='squad_cells',
        ),
        migrations.RemoveField(
            model_name='squadorder',
            name='subject_materials',
        ),
        migrations.RemoveField(
            model_name='squadorder',
            name='time_period',
        ),
        migrations.AddField(
            model_name='lecture',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_lectures', to='subjects.TimePeriod'),
        ),
        migrations.AddField(
            model_name='squadcell',
            name='subject_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_cells', to='subjects.SubjectMaterials'),
        ),
        migrations.DeleteModel(
            name='SquadOrder',
        ),
    ]
