# Generated by Django 2.2.5 on 2019-12-27 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_remove_financeclosed_fixed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeclosed',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
