# Generated by Django 2.2.5 on 2020-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_financeclosed_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='filter_course_connect',
        ),
    ]
