# Generated by Django 2.0.1 on 2018-11-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_auto_20181126_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time_period',
        ),
    ]
