# Generated by Django 2.0.1 on 2018-11-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_remove_lecture_time_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadcell',
            options={'ordering': ['date', 'cell']},
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='time_period',
        ),
        migrations.AddField(
            model_name='squadcell',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_squad_cells', to='subjects.Cell'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='squads',
            field=models.ManyToManyField(related_name='subjects', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers_subjects', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='subjects',
            field=models.ManyToManyField(related_name='subject_categories', to='subjects.Subject'),
        ),
    ]
