# Generated by Django 2.2.5 on 2020-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200527_1859'),
        ('subjects', '0016_remove_subject_filter_course_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='filter_course_connect',
            field=models.ManyToManyField(related_name='filter_course_connect', to='accounts.Skill'),
        ),
    ]
