# Generated by Django 2.2.5 on 2020-05-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200527_1911'),
        ('subjects', '0017_subject_filter_course_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='filter_course_connect',
        ),
        migrations.AddField(
            model_name='subject',
            name='filter_subject_connect',
            field=models.ManyToManyField(related_name='filter_subject_connect', to='accounts.Skill'),
        ),
    ]
