# Generated by Django 2.0.1 on 2018-11-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_auto_20181127_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadcell',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_cells', to='subjects.TimePeriod'),
        ),
    ]
