# Generated by Django 2.2.5 on 2020-05-27 21:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200527_2140'),
        ('squads', '0018_auto_20200527_2140'),
        ('schools', '0014_auto_20200527_2120'),
        ('subjects', '0018_auto_20200527_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='age',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='filter_subject_connect',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.CreateModel(
            name='FilterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('crm_notices', models.IntegerField(default=0)),
                ('payment_notices', models.IntegerField(default=0)),
                ('payment', models.TextField(blank=True, default='all', null=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_data', to='accounts.Profile')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.Office')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='squads.Squad')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='subjects.Subject')),
                ('subject_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='schools.SubjectCategory')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosed_by', to='accounts.Profile')),
            ],
        ),
    ]
