# Generated by Django 2.0.1 on 2018-11-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_squadcell_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadcell',
            name='subject_materials',
        ),
        migrations.AddField(
            model_name='squadcell',
            name='subject_materials',
            field=models.ManyToManyField(related_name='material_cells', to='subjects.SubjectMaterials'),
        ),
    ]
