# Generated by Django 2.2.5 on 2020-05-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0019_auto_20200527_2142'),
        ('subjects', '0019_auto_20200527_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeclosed',
            name='need_money',
        ),
        migrations.AddField(
            model_name='financeclosed',
            name='bill_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_closed', to='squads.BillData'),
        ),
    ]
