# Generated by Django 2.0.1 on 2018-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_auto_20181127_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadcell',
            options={'ordering': ['date', 'time_period']},
        ),
    ]
