# Generated by Django 2.0.1 on 2018-11-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_manager'),
        ('subjects', '0020_auto_20181127_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('present', models.TextField(default='')),
                ('grade', models.IntegerField(default=-1)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='accounts.Profile')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance', to='subjects.Subject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
