# Generated by Django 2.2.5 on 2020-05-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_auto_20200527_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinanceClosed',
            new_name='SubjectBill',
        ),
    ]
