# Generated by Django 2.2.5 on 2020-05-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_auto_20200527_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image_back',
        ),
    ]
