# Generated by Django 2.0.1 on 2018-11-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0008_auto_20181128_0424'),
        ('subjects', '0021_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='squad_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_attendances', to='subjects.SquadCell'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_attendances', to='squads.SquadWeek'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='subjects.Subject'),
        ),
    ]
