# Generated by Django 2.2.5 on 2020-06-02 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_remove_subject_image_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
