# Generated by Django 2.2.5 on 2020-06-03 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0023_filterdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectbill',
            name='course_bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subjectbill',
            name='lesson_bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
    ]
