# Generated by Django 2.0.1 on 2018-11-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0023_auto_20181128_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['squad_cell']},
        ),
    ]
