# Generated by Django 2.0.1 on 2018-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_auto_20181128_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='number_of_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
