# Generated by Django 2.2.5 on 2020-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_auto_20200603_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterdata',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
