# Generated by Django 2.0.1 on 2018-11-30 06:14

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0025_subject_number_of_lectures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='image',
            new_name='image_banner',
        ),
        migrations.AddField(
            model_name='subject',
            name='image_icon',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=subjects.models.upload_location, width_field='width_field'),
        ),
    ]
