# Generated by Django 2.2.5 on 2020-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0025_auto_20200606_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
