# Generated by Django 2.0.1 on 2018-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0026_auto_20181130_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cabinet',
            field=models.TextField(default=''),
        ),
    ]
