# Generated by Django 2.2.5 on 2020-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0024_auto_20200604_0214'),
        ('subjects', '0026_auto_20200614_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prefered_squads',
            field=models.ManyToManyField(related_name='prefered_subjects', to='squads.Squad'),
        ),
    ]
