# Generated by Django 2.0.1 on 2018-12-09 05:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0027_subject_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cache_newcells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='cache_oldcells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
