# Generated by Django 2.2.5 on 2020-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0027_subject_prefered_squads'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='subject_type',
            field=models.TextField(blank=True, default='all', null=True),
        ),
    ]
