# Generated by Django 2.0.1 on 2018-12-09 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0028_auto_20181209_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cache_newcells',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cache_oldcells',
        ),
        migrations.AddField(
            model_name='subject',
            name='cache_newlects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='cache_oldlects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[], size=None),
        ),
    ]
