# Generated by Django 2.2.5 on 2020-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_bill_day_diff'),
        ('squads', '0025_auto_20200623_0716'),
        ('subjects', '0028_filterdata_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='office_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_choosed_by', to='schools.Office'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='squad_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_choosed_by', to='squads.Squad'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='subject_category_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_choosed_by', to='schools.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='subject_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_choosed_by', to='subjects.Subject'),
        ),
    ]
