# Generated by Django 2.2.5 on 2020-07-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0029_auto_20200623_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['subject_materials', 'student', 'squad']},
        ),
    ]
