# Generated by Django 2.0.1 on 2018-12-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0029_auto_20181209_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cache_newlects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cache_oldlects',
        ),
    ]
