# Generated by Django 2.0.1 on 2018-12-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0030_auto_20181209_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['subject_materials']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='squad_cell',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='week',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subjects.SubjectMaterials'),
        ),
    ]
