# Generated by Django 2.0.1 on 2018-12-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0031_auto_20181209_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['student']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject_materials',
        ),
        migrations.AddField(
            model_name='attendance',
            name='squad_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subjects.SquadCell'),
        ),
    ]
