# Generated by Django 2.0.1 on 2018-12-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0032_auto_20181209_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendances', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hisattendance', to='accounts.Profile'),
        ),
    ]
