# Generated by Django 2.0.1 on 2018-12-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0033_auto_20181209_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='number',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_atts', to='subjects.SubjectMaterials'),
        ),
    ]
