# Generated by Django 2.0.1 on 2018-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181217_1505'),
        ('subjects', '0034_auto_20181209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='hissubjects', to='accounts.Profile'),
        ),
    ]
