# Generated by Django 2.0.1 on 2018-12-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0015_squad_cabinet'),
        ('subjects', '0035_subject_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject_materials',
        ),
        migrations.AddField(
            model_name='attendance',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squad_attendances', to='squads.Squad'),
        ),
    ]
