# Generated by Django 2.0.1 on 2018-12-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0036_auto_20181226_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['squad_cell', 'student']},
        ),
    ]
