# Generated by Django 2.0.1 on 2018-12-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0037_auto_20181226_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_atts', to='subjects.SubjectMaterials'),
        ),
    ]
