# Generated by Django 2.0.1 on 2018-12-30 15:30

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0038_attendance_subject_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='height_field2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='height_field3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image_back',
            field=models.ImageField(blank=True, height_field='height_field3', null=True, upload_to=subjects.models.upload_location, width_field='width_field3'),
        ),
        migrations.AddField(
            model_name='subject',
            name='width_field2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='width_field3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image_banner',
            field=models.ImageField(blank=True, height_field='height_field2', null=True, upload_to=subjects.models.upload_location, width_field='width_field2'),
        ),
    ]
