# Generated by Django 2.0.1 on 2018-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0039_auto_20181230_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color_back',
            field=models.TextField(default=''),
        ),
    ]
