# Generated by Django 2.0.1 on 2019-01-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190127_0121'),
        ('subjects', '0041_auto_20190121_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaterials',
            name='done_by',
            field=models.ManyToManyField(related_name='done_subject_materials', to='accounts.Profile'),
        ),
    ]
