# Generated by Django 2.1.7 on 2019-02-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0042_subjectmaterials_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default=119, on_delete=django.db.models.deletion.CASCADE, related_name='madegrades', to='accounts.Profile'),
        ),
    ]
