# Generated by Django 2.1.7 on 2019-02-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_curator'),
        ('subjects', '0043_auto_20190216_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcategory',
            name='subjects',
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_attendances', to='schools.School'),
        ),
        migrations.AddField(
            model_name='cell',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_cells', to='schools.School'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_lectures', to='schools.School'),
        ),
        migrations.AddField(
            model_name='squadcell',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_squad_cells', to='schools.School'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_subjects', to='schools.School'),
        ),
        migrations.AddField(
            model_name='subjectmaterials',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_materials', to='schools.School'),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_periods', to='schools.School'),
        ),
        migrations.DeleteModel(
            name='SubjectCategory',
        ),
    ]
