# Generated by Django 2.1.7 on 2019-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20190217_1514'),
        ('subjects', '0044_auto_20190217_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='students',
            field=models.ManyToManyField(related_name='histime_periods', to='accounts.Profile'),
        ),
    ]
