# Generated by Django 2.1.7 on 2019-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_profile_salary'),
        ('subjects', '0045_timeperiod_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadcell',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='school',
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='subject_materials',
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='squadcell',
            name='week',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['subject', 'squad', 'student']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='squad_cell',
        ),
        migrations.AddField(
            model_name='lecture',
            name='people',
            field=models.ManyToManyField(related_name='hislectures', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='SquadCell',
        ),
    ]
