# Generated by Django 2.1.7 on 2019-02-24 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0046_auto_20190222_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='subjectmaterials',
            name='dates_for_squads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subjectmaterials',
            name='squad_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
