# Generated by Django 2.1.7 on 2019-02-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0047_auto_20190224_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaterials',
            name='dates_for_squads',
        ),
        migrations.RemoveField(
            model_name='subjectmaterials',
            name='squad_ids',
        ),
    ]
