# Generated by Django 2.1.7 on 2019-02-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0048_auto_20190224_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeperiod',
            old_name='students',
            new_name='people',
        ),
    ]
