# Generated by Django 2.1.7 on 2019-02-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190227_0611'),
        ('subjects', '0049_auto_20190226_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='subject',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_subjects', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='subject',
            name='cabinett',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_subjects', to='schools.School'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_subhects', to='schools.SubjectCategory'),
        ),
    ]
