# Generated by Django 2.1.7 on 2019-02-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0050_auto_20190227_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cabinett',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_subjects', to='schools.Cabinett'),
        ),
    ]
