# Generated by Django 2.1.7 on 2019-02-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0051_auto_20190227_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_subjects', to='schools.SubjectCategory'),
        ),
    ]
