# Generated by Django 2.1.7 on 2019-03-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20190301_0303'),
        ('subjects', '0052_auto_20190228_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cabinett',
        ),
        migrations.AddField(
            model_name='lecture',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_lecture', to='schools.Cabinet'),
        ),
        migrations.AddField(
            model_name='subject',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_subjects', to='schools.Office'),
        ),
    ]
