# Generated by Django 2.1.7 on 2019-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0053_auto_20190301_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
