# Generated by Django 2.1.7 on 2019-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0054_subject_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='color_back',
            field=models.TextField(default=''),
        ),
    ]
