# Generated by Django 2.1.7 on 2019-03-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0055_lecture_color_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='color_back',
        ),
    ]
