# Generated by Django 2.1.7 on 2019-03-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20190309_1057'),
        ('squads', '0019_auto_20190302_0716'),
        ('subjects', '0056_remove_lecture_color_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='squads.Squad')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='subjects.Subject')),
            ],
        ),
    ]
