# Generated by Django 2.1.7 on 2019-03-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0057_cacheattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheattendance',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='cacheattendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_attendance', to='subjects.Subject'),
        ),
    ]
