# Generated by Django 2.1.7 on 2019-03-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0058_auto_20190309_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.Day'),
        ),
    ]
