# Generated by Django 2.1.7 on 2019-03-15 04:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0059_lecture_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='squad_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='start_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
