# Generated by Django 2.1.7 on 2019-03-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0061_auto_20190315_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='cacheattendance',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiscache', to='accounts.Profile'),
        ),
    ]
