# Generated by Django 2.1.7 on 2019-03-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0062_auto_20190316_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['subject_materials', 'squad', 'student']},
        ),
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['number']},
        ),
    ]
