# Generated by Django 2.1.7 on 2019-04-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190407_1713'),
        ('subjects', '0063_auto_20190320_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_lectures', to='schools.SubjectAge'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_lectures', to='schools.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_lectures', to='schools.Office'),
        ),
    ]
