# Generated by Django 2.1.7 on 2019-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20190426_1035'),
        ('subjects', '0064_auto_20190410_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='rating_choices',
            field=models.ManyToManyField(default=1, related_name='rating_subject_choice', to='accounts.Profile'),
        ),
    ]
