# Generated by Django 2.1.7 on 2019-04-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0065_subject_rating_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='rating_choices',
        ),
    ]
