# Generated by Django 2.1.7 on 2019-05-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0066_remove_subject_rating_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='number_of_lectures',
        ),
        migrations.AddField(
            model_name='subject',
            name='cabinet',
            field=models.CharField(default='', max_length=250),
        ),
    ]
