# Generated by Django 2.1.7 on 2019-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0067_auto_20190507_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='subject',
            name='number_of_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
