# Generated by Django 2.1.7 on 2019-05-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0068_auto_20190507_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterials',
            options={'ordering': ['id']},
        ),
    ]
