# Generated by Django 2.1.7 on 2019-05-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190507_2111'),
        ('subjects', '0069_auto_20190508_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='number_of_lectures',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='squad_ids',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='start_dates',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.Profile'),
        ),
    ]
