# Generated by Django 2.1.7 on 2019-05-11 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190507_2111'),
        ('subjects', '0070_auto_20190509_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_subjects', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_subjects', to='accounts.Profile'),
        ),
    ]
