# Generated by Django 2.1.7 on 2019-05-11 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0071_auto_20190511_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='squad_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='start_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), default=list, size=None),
        ),
    ]
