# Generated by Django 2.1.7 on 2019-05-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0072_auto_20190511_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_attendances', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hisgrades', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madegrades', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_lectures', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='subjectmaterials',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_materials', to='schools.School'),
        ),
    ]
