# Generated by Django 2.1.7 on 2019-05-19 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0073_auto_20190519_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='person_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='lecture',
            name='person_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
