# Generated by Django 2.2.1 on 2019-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0074_auto_20190519_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='number_of_materials',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
