# Generated by Django 2.2.1 on 2019-06-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0075_subject_number_of_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'ordering': ['id']},
        ),
    ]
