# Generated by Django 2.2.1 on 2019-07-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0076_auto_20190623_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id']},
        ),
    ]
