# Generated by Django 2.2.1 on 2019-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0077_auto_20190702_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='office',
        ),
    ]
