# Generated by Django 2.2.4 on 2019-08-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('subjects', '0078_remove_subject_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='schools.SubjectLevel'),
        ),
    ]
