# Generated by Django 2.2.4 on 2019-08-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('subjects', '0079_subject_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='age',
        ),
        migrations.AddField(
            model_name='subject',
            name='age',
            field=models.ManyToManyField(related_name='age_subjects', to='schools.SubjectAge'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ManyToManyField(related_name='category_subjects', to='schools.SubjectCategory'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ManyToManyField(related_name='level_subjects', to='schools.SubjectLevel'),
        ),
    ]
