# Generated by Django 2.2.4 on 2019-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('subjects', '0080_auto_20190831_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.ManyToManyField(related_name='level_lectures', to='schools.SubjectLevel'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='age',
        ),
        migrations.AddField(
            model_name='lecture',
            name='age',
            field=models.ManyToManyField(related_name='age_lectures', to='schools.SubjectAge'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='category',
        ),
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.ManyToManyField(related_name='category_lectures', to='schools.SubjectCategory'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='office',
        ),
        migrations.AddField(
            model_name='lecture',
            name='office',
            field=models.ManyToManyField(related_name='office_lectures', to='schools.Office'),
        ),
    ]
