# Generated by Django 2.2.4 on 2019-09-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20190831_2022'),
        ('subjects', '0081_auto_20190901_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='office',
        ),
        migrations.AddField(
            model_name='lecture',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_lectures', to='schools.Office'),
        ),
    ]
