# Generated by Django 2.2.5 on 2019-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0082_auto_20190901_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cost_period',
            field=models.CharField(default='month', max_length=250),
        ),
    ]
