# Generated by Django 2.2.5 on 2019-09-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0083_subject_cost_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
