# Generated by Django 2.2.5 on 2019-09-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0084_auto_20190925_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'ordering': ['start']},
        ),
    ]
