# Generated by Django 2.2.5 on 2019-10-08 10:25

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0085_auto_20190930_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='height_field2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='height_field3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='width_field2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='width_field3',
        ),
        migrations.AlterField(
            model_name='subject',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to=subjects.models.upload_location),
        ),
    ]
