# Generated by Django 2.2.5 on 2019-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_auto_20191008_1008'),
        ('subjects', '0086_auto_20191008_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='filter_course_connect',
            field=models.ManyToManyField(related_name='filter_course_connect', to='accounts.Skill'),
        ),
    ]
