# Generated by Django 2.2.5 on 2019-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_auto_20191016_1146'),
        ('subjects', '0087_subject_filter_course_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='filter_options',
            field=models.ManyToManyField(related_name='subjects', to='schools.SchoolFilterOption'),
        ),
    ]
