# Generated by Django 2.2.5 on 2019-10-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0088_subject_filter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeperiod',
            name='people',
        ),
    ]
