# Generated by Django 2.2.5 on 2019-10-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20191021_0322'),
        ('subjects', '0089_remove_timeperiod_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit', models.TextField(default='')),
                ('old', models.CharField(max_length=250)),
                ('new', models.CharField(max_length=250)),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_histories', to='accounts.Profile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_histories', to='subjects.Subject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
