# Generated by Django 2.2.5 on 2019-10-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20191021_0322'),
        ('subjects', '0090_subjecthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecthistory',
            name='new',
        ),
        migrations.RemoveField(
            model_name='subjecthistory',
            name='old',
        ),
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit', models.TextField(default='')),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_histories', to='accounts.Profile')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_histories', to='subjects.Lecture')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
