# Generated by Django 2.2.5 on 2019-10-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20191021_0322'),
        ('subjects', '0091_auto_20191023_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterialsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit', models.TextField(default='')),
                ('action_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='accounts.Profile')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_histories', to='subjects.SubjectMaterials')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LectureHistory',
        ),
    ]
